language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe
  # Push to binstar.

env:
  matrix:
    - python=2.7  CONDA_PY=27

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
after_success:
  - echo "after_success"
  - bash devtools/ci/after_sucess.sh
